'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SimonSays.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property blankImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blankImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledBlueOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledBlueOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledBlueOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledBlueOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledCyanOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledCyanOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledCyanOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledCyanOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledGreenOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledGreenOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledGreenOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledGreenOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledOrangeOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledOrangeOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledOrangeOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledOrangeOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledPinkOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledPinkOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledPinkOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledPinkOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledPurpleOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledPurpleOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledPurpleOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledPurpleOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledRedOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledRedOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledRedOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledRedOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledWhiteOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledWhiteOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledWhiteOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledWhiteOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledYellowOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledYellowOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledYellowOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledYellowOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
